name: ${project.name}
author: LimeByte
version: ${project.version}
description: ${project.description}

main: me.limebyte.endercraftessentials.EndercraftEssentials
load: POSTWORLD

website: ${project.url}
database: false

commands:
    formation:
        description: Bedrock formation checker.
        usage: /<command> <radius>
    vanish:
        description: Poof!
        aliases: v
        permission: ee.vanish
        usage: /<command>
    spawn:
        description: Teleport to the spawn.
        usage: /<command>
        
permissions:
    ee.vanish:
        default: op